config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/users/about', to: 'users#about'
  resources :users
  resources :results
  resources :games
  resources :questions
  get '/', to: 'users#welcome', as: 'welcome'
  post '/answer', to: 'games#answer', as: 'answer'
  get '/end', to: 'users#end', as: 'end'
  get '/users/:id/my_games', to: 'users#my_games'
end

app/views/games/show.html.erb
<div id ="all">

<nav class="navbar-nav  navbar-light " style="background-color: #e3f2fd;">



<h1 ALIGN=CENTER class = "font-weight-bold btn btn-lg btn-success">Score: <%= "#{@game.score}" %></h1><br>



<%= image_tag(image_url(@question.location), size: "512x320", :class => "rounded mx-auto d-block")%><br><br>



<h3 ALIGN=CENTER >Choose Answer:</h>



<% @ans.each do |x| %>
<%= form_tag answer_path, :class => 'btn btn-outline-dark btn-lg btn-block' do  %>
 <%= hidden_field_tag :id, @game.id %>
 <%= hidden_field_tag :question_id, @question.id %>
 <%= hidden_field_tag :result_id, @game_result.id %>
  <%= hidden_field_tag :chosen, x %>
 <%= submit_tag "#{x}"  %>
<% end %>
<% end %>





<!-- <a href="/">Main Menu</a><br> -->

<!-- 1. main game page
2. logo
3. picture centered
4. three random choices to choose from
5. score on top right that updates
6. sound effect or show correct/wrong answer whichever is easier
7. cycle to next answer till finished
8. stretch goal - timer to limit time to answer
9. stretch goal - anthem music? -->

app/views/users/about.html.erb
<div class="container">

<nav class="navbar navbar-expand-lg navbar-light " style="background-color: #e3f2fd;">
  <div class="container">
   <a href="/">Log Out</a>
 </div>
  <div class="container">
   <a href="/users/<%=@user.id%>">Back to <%=@user.name%> Page</a>
 </div>
 <div class="container">
  <a href="/users/">High Scores</a>
</div>
</nav>

 <h1 align = "center">About</h1><br>

 <p align = "center">
  This is a Killer Cat Production (Ranjit Saimbi and George Wong).
   <br><br>
  Test your knowledge of <a href="https://http.cat/"> Cats and Status Codes</a> and World Flags.
</p><br>

<div class="text-center">
<img src="https://img.buzzfeed.com/buzzfeed-static/static/2013-10/campaign_images/webdr01/11/6/how-well-do-you-know-the-flags-of-the-world-1-30922-1381485714-9_big.jpg" height="50%" width="50%">
</div>

<style>
#foot {
  position: absolute;
  left: 20;
  bottom: 0;
  width: 80%;
  text-align: center;
}
</style>

<div id= "foot" class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;"">
  <p> </p>
</div>

app/views/users/end.html.erb
<div class="container">

<nav class="navbar navbar-expand-lg navbar-light " style="background-color: #e3f2fd;"><br>
<a> <%= link_to "Back to Your page", user_path(@game.user) %></a>
 </nav>





<div class="container">
<h1>Congratulations <%= @game.user.name.capitalize %>!</h1>
<h3><%= "Your score is #{@game.score}" %></h3>
<h3><%= "You are ranked # #{Game.order(:score).all.reverse.index(@game) + 1}" %></h3>
<br>

<ul class="list-group">
  <li class="list-group-item active">Your answers:</li>
  <% @game.results.each do |r|%>
  <li class="list-group-item"> <%= r.question.answer %> : <% if r.correct %> <font color="green">CORRECT</font> <% else %><font color="red">WRONG</font> <% end %></li>
  <% end %>
</ul>
<br>

<br>
</div>

<style>
#foot {
  position: absolute;
  left: 20;
  bottom: 0;
  width: 80%;
  text-align: center;
}
</style>

<div id= "foot" class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;"">
  <p> </p>
</div>

app/views/users/index.html.erb
<div class="container">

<nav class="navbar navbar-expand-lg navbar-light " style="background-color: #e3f2fd;">
  <div class="container">
   <a href="/users/<%=@user.id%>">Back to <%=@user.name%> Page</a>
 </div>
 <div class="container">
    <a href="/users/<%=@user.id%>/my_games">My Games</a>
 </div>
<div class="container">
   <a href="/users/about">About</a>
</div>
 </nav>

<br>
<ul class="list-group">
  <li class="list-group-item active">Top 3 Scores</li>
<% @games.order(score: :desc).first(3). each do |g| %>
<li class="list-group-item"> <%= g.score  %> - <%= g.user.name  %></li>
<% end %>
</ul>
<br>
<ul class="list-group">
    <li class="list-group-item active">Top 5 Correct Questions</li>
<% @top_5_questions.each do |k,v| %>
<li class="list-group-item"> <%= k%> - <%= v%> </li>
<% end %>
</ul>
<br>
<ul class="list-group">
    <li class="list-group-item active">Top 5 Incorrect Questions</li>
<% @bottom_5_questions.each do |k,v| %>
<li class="list-group-item"> <%= k%> - <%= v%> </li>
<% end %>
</ul><br>

<style>
#foot {
  position: relative;
  left: 20;
  bottom: 0;
  width: 100%;
  text-align: center;
}
</style>

<div id= "foot" class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;"">
  <p> </p>
</div>

app/views/users/my_games.html.erb
<% if flash[:notice] %>
   <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
 <% end %>
 <br>


 <div class="container">

 <nav class="navbar navbar-expand-lg navbar-light " style="background-color: #e3f2fd;">
   <div class="container">
    <a href="/users/<%=@user.id%>">Back to <%=@user.name%> Page</a>
  </div>
  <div class="container">
   <a href="/users/">High Scores</a>
 </div>
 <div class="container">
    <a href="/users/about">About</a>
 </div>
  </nav>
<br>
<ul class="list-group">
<li class="list-group-item active"><%=@user.name%> Stats:</li>
<li class="list-group-item">Top Score: <%= @my_games.map{|g|g.score}.max %></li>
<li class="list-group-item">Rank: <%=Game.order(:score).all.reverse.index(@top_game) + 1 %> </li>
<li class="list-group-item">Average Score: <%= @my_games.map{|g|g.score}.inject(0){|sum,x| sum + x }/ @my_games.count %></li>
<br>
</ul>

<ul class="list-group">
<li class="list-group-item active">Game History:</li>
<% @my_games.each do |g|%>
<li class="list-group-item list-group-item-dark"> Score: <%= g.score %>
</li>

  <% g.results.each do |r|%>
  <li class="list-group-item"> <%= r.question.answer %> : <% if r.correct %> <font color="green">CORRECT</font>  <% else %><font color="red">WRONG</font><% end %></li>
  <% end %>
</ul>
<%= button_to "Delete Game", {:controller => :games,
    :action => 'destroy', :id => g.id }, :method => :delete %>
<% end %>
<br>

<style>
#foot {
  position: relative;
  left: 20;
  bottom: 0;
  width: 100%;
  text-align: center;
}
</style>

<div id= "foot" class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;"">
  <p> </p>
</div>

app/views/users/show.html.erb
<div class="container">

<nav class="navbar navbar-expand-lg navbar-light " style="background-color: #e3f2fd;">
  <div class="container">
   <a href="/">Log Out</a>
 </div>
 <div class="container">
  <a href="/users/">High Scores</a>
</div>
<div class="container">
   <a href="/users/<%=@user.id%>/my_games">My Games</a>
</div>
<div class="container">
   <a href="/users/about">About</a>
</div>
 </nav>
<div class="text-center">
<img src="https://cdn1.bigcommerce.com/server4100/deb25/products/572/images/5125/cat_flag_sm_wht__72628.1466549182.1280.1280.jpg" height="40%" width="40%">
<h2 class="display-7">Welcome <%= @user.name.capitalize%>! </h2><br>

<%= button_to "New Game",
    {
      action: "create",
      controller: "games",
      id: @user.id
    },
    method: "post"
%>
</div>

<style>
#foot {
  position: absolute;
  left: 20;
  bottom: 0;
  width: 80%;
  text-align: center;
}
</style>

<div id= "foot" class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;"">
  <p> </p>
</div>

app/views/users/welcome.html.erb
<div class="container">

<nav class="navbar navbar-expand-lg navbar-light " style="background-color: #e3f2fd;">
  <div class="container">
   <a href="/">Main Menu</a>
 </div>
 <div class="container">
  <a href="/users/">High Scores</a>
</div>
<div class="container">
   <a href="/users/about">About</a>
</div>
 </nav>
<div class="text-center">
<img src="https://cdn1.bigcommerce.com/server4100/deb25/products/572/images/5125/cat_flag_sm_wht__72628.1466549182.1280.1280.jpg" height="40%" width="40%">
<h2 class="display-7">A strategy game of mystery and intrigue (not really)</h2><br>
<div class="form-group">
  <%= form_for(@user) do |f| %>
    <label> Enter your user name:</label><br>
    <%= f.text_field :name %><br><br>
    <%= f.submit %><br>
  <% end %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </div>
  <% end %>
</div>
</div>




<style>
#foot {
  position: absolute;
  left: 20;
  bottom: 0;
  width: 80%;
  text-align: center;
}
</style>

<div id= "foot" class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;"">
  <p> </p>
</div>


<!-- User starts here.

1. get user details
2. link to about
3. link to high scores
2. basic logo
3. stretch goal - show top 5 high scores "NAME is current high score, can you beat him?" -->